# fly.toml app configuration file generated for smij on 2023-09-30T13:21:42-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "smij"
primary_region = "ord"

[build]

[env]
  HOSTNAME = "smij.io"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]
